[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cctp_burn_hook_wrapper = "4MvgjyyGBGqqjzFV4xQM7Ncnr4Ny2bHMPyi7fyTuemWP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[idl]
out = "target/idl"
